dir_name: "/"
data:
  name: 'forcast'
  data_name: 'weather'
  seq_len: 96
  data_path: /dataset/all_six_datasets/
  batch_size: 32
  num_workers: 0
  max_n: 5
  pred_step: 96
model:
  concept_dim: 64
  task_type: "forcast"
  kernel_size: 25
  num_classes: 10
  d_inp: auto
  max_len: auto
  total_len: auto
  n_classes: auto
  enc_args:
    d_model: 16
    max_len: 30
    desired_threshold: 0.6
    fixed_max_segments: 10
    fixed_max_len: 30
    d_pe: 1
    trimmer_types: ['Decomposition']
    input_dim: 8
    hidden_size: 32
    num_layers: 2
    encoder_type: 'tcn'
    n_layers: 2
    pred_step: 96
    device: cuda
  dec_args:
    decoder_type: 'pos-attention'
    input_dim: 128
    hidden_dim: 64
    pred_step: 96
    initial_bias_value: 0.0
    dropout: 0.3
train:
  train_refer_model: True
  lr: 0.003
  weight_decay: 0.001
  epochs: 200
  save_path: "/output/saved_models"
  visualize: True
  alpha: True
test:
  dir_name: "/output/results"
reproduc:
  seed: 42
  benchmark: False
  deterministic: True
