dir_name: "./output/debug/"
data:
  name: "UCR"
  data_name: "Wafer"
  data_path: "./dataset/UCR"
  seq_len: 200
  batch_size: 64
  num_workers: 0
model:
  concept_dim: 32
  task_type: "classify"
  kernel_size: 25
  num_classes: 1
  d_inp: auto
  max_len: auto
  total_len: auto
  n_classes: auto
  enc_args:
    d_model: 16
    max_len: 50
    desired_threshold: 0.6
    fixed_max_segments: 10
    fixed_max_len: 72
    d_pe: 1
    trimmer_types: ['Decomposition']
    input_dim: 8
    hidden_size: 32
    num_layers: 2
    encoder_type: 'tcn'
    n_layers: 2
    pred_step: 1
    device: cuda
  dec_args:
    decoder_type: 'pos-attention'
    input_dim: 128
    hidden_dim: 64
    pred_step: 1
    initial_bias_value: 0.0
    dropout: 0.0
train:
  train_refer_model: True
  lr: 0.0003
  weight_decay: 0.0001
  epochs: 50
  save_path: "./output/saved_models"
  visualize: True
  alpha: False
test:
  dir_name: "./output/results"
reproduc:
  seed: 307
  benchmark: False
  deterministic: True
